//
// Created by toor on 6/26/18.
//

#ifndef MODERNCPPDESIGNPATTERN_FACTORYMETHOD_H
#define MODERNCPPDESIGNPATTERN_FACTORYMETHOD_H


class FactoryMethod {

};


#endif //MODERNCPPDESIGNPATTERN_FACTORYMETHOD_H
